name: Package Dashboard

on:
  push:
    branches:
      - main
    paths:
      - 'dashboard/**'
      - '.github/workflows/zipDaseboard.yml'

jobs:
  package_dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: Package dashboard
        run: zip -r dashboard.zip dashboard

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automatically package dashboard changes"
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
